version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx-node
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "48MB"

  api01: &api
    image: caduxl007/rinha-backend-2025:latest
    container_name: rinha-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - MAX_PARALLELISM=5
    depends_on:
      - redis
    volumes:
      - redis_data:/data
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "108MB"

  api02:
    <<: *api
    container_name: rinha-api-2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis_data: